services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5433/db?schema=public"

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
